### ISSUE TITLE
 Implement e2e tests in OF operator using KUTTL

### ISSUE THREAD

**Issue by bacherfl** [open-feature/open-feature-operator#391]
# Short Abstract 

Currently, the E2E tests are using a set of shell scripts that apply a FeatureFlag resource and then retrieve the value of a feature flag via the flagd API to evaluate the response.
These tests could potentially benefit from using KUTTL (https://kuttl.dev/), with which we have made good experiences in KLT (see https://github.com/keptn/lifecycle-toolkit/tree/main/test/integration).

# Why 

This framework allows to define test cases using Kubernetes manifests that are applied in one step, and then be evaluated using assertions that check for certain conditions being available on kubernetes resources (e.g. the status of a deployment). The framework will also take care of tasks such as isolating test scenarios from each other by running them in separate namespaces, as well as implementing the retry/timeout logic for the evaluation of the assertions.

The validation steps that are currently done via bash scripts can be reused by executing those in a K8s Job - Kuttl can then validate the status of that job.

Also, KUTTL may open the door for more complex e2e test scenarios with an annotated deployment being applied and then asserting if the flagd sidecar has successfully been injected

# Tasks

- [ ] Migrate the existing e2e test to Kuttl
- [ ] Add a command to the Makefile to execute these tests
- [ ] Execute these tests in the pipeline

# References

A proof of concept for this can be found in the following PR: https://github.com/bacherfl/open-feature-operator/pull/1 - this PR already wires up everything that is needed to also execute the tests in the pipeline, so with some further polishing it should be in a state in which it can be merged

**Comment by RealAnna** [comment]
I would like to take this one!
