### ISSUE TITLE
[Tracking] Move API to v1beta1

### ISSUE THREAD

**Issue by odubajDT** [open-feature/open-feature-operator#528]
## Goal

The goal of this issue is to move the OFO API to `beta` as a preparation for future stable release of OFO 1.x.

### Details

This issue is a follow-up of a research made and tracked under https://github.com/open-feature/open-feature-operator/issues/352 together with a PoC created to have a better overview what needs to be done in order to reach our goal.

```[tasklist]
### Tasks
- [ ] https://github.com/open-feature/open-feature-operator/issues/529
- [ ] https://github.com/open-feature/flagd/issues/983
- [ ] https://github.com/open-feature/open-feature-operator/issues/531
- [ ] https://github.com/open-feature/open-feature-operator/issues/433
- [ ] https://github.com/open-feature/open-feature-operator/issues/532
- [ ] https://github.com/open-feature/open-feature-operator/issues/517
- [ ] https://github.com/open-feature/open-feature-operator/issues/537
- [ ] https://github.com/open-feature/open-feature-operator/issues/534
- [ ] https://github.com/open-feature/open-feature-operator/issues/533
```

**Comment by odubajDT** [comment]
Closing this tracking issue, as all of the sub-tasks were done
